repos:
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.0
    hooks:
      - id: pylint
        name: Rodando Pylint
        entry: pylint
        language: python
        types: [python]
        args:
          - "--max-line-length=120"
          - "--disable=C0114"