repos:
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.0
    hooks:
      - id: pylint
        name: Rodando Pylint
        entry: pylint
        # Use the project's active Python environment so pylint can import project deps
        # (pre-commit by default creates isolated envs which don't have SQLAlchemy/pytest)
        language: system
        types: [python]
        args:
          - "--max-line-length=120"
          - "--disable=C0114"